const ARCHWAY_CONTRACT_ADDRESS = import.meta.env.VITE_APP_ARCHWAY_CONTRACT_ADDRESS;
const INJECTIVE_CONTRACT_ADDRESS = import.meta.env.VITE_APP_INJECTIVE_CONTRACT_ADDRESS;
const NEUTRON_CONTRACT_ADDRESS = import.meta.env.VITE_APP_NEUTRON_CONTRACT_ADDRESS;

export const CosmosContracts = {
  archway: ARCHWAY_CONTRACT_ADDRESS,
  injective: INJECTIVE_CONTRACT_ADDRESS,
  neutron: NEUTRON_CONTRACT_ADDRESS,
};
